server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:shopsphere}?currentSchema=products
    username: ${POSTGRES_USER:shopsphere}
    password: ${POSTGRES_PASSWORD:shopsphere}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: products
  flyway:
    enabled: true
    default-schema: products
    schemas: products
    create-schemas: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
