import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const APIs={products:import.meta.env.VITE_PRODUCT_API||'http://localhost:8081',users:import.meta.env.VITE_USER_API||'http://localhost:8082',orders:import.meta.env.VITE_ORDER_API||'http://localhost:8083',payments:import.meta.env.VITE_PAYMENT_API||'http://localhost:8084'};

function App(){
 const [products,setProducts]=useState([]),[cart,setCart]=useState([]),[user,setUser]=useState(null),[name,setName]=useState('Demo User'),[email,setEmail]=useState('demo@example.com'),[password,setPassword]=useState('password'),[message,setMessage]=useState('');
 useEffect(()=>{fetch(`${APIs.products}/api/products`).then(r=>r.json()).then(setProducts).catch(()=>setMessage('Product service is unavailable.'));},[]);
 const register=async()=>{setMessage(''); const r=await fetch(`${APIs.users}/api/users/register`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email,password})}); if(!r.ok){setMessage(await r.text());return;} setUser(await r.json());setMessage('User registered.');};
 const add=p=>setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,quantity:i.quantity+1}:i):[...c,{...p,quantity:1}]});
 const checkout=async()=>{if(!user){setMessage('Register the demo user first.');return;} const items=cart.map(i=>({productId:i.id,quantity:i.quantity,unitPrice:i.price})); const total=items.reduce((s,i)=>s+i.quantity*Number(i.unitPrice),0); const ro=await fetch(`${APIs.orders}/api/orders`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:user.id,items})}); if(!ro.ok){setMessage(await ro.text());return;} const order=await ro.json(); const rp=await fetch(`${APIs.payments}/api/payments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId:order.id,amount:total})}); const payment=await rp.json(); setMessage(`Order #${order.id} created — payment ${payment.status}.`);setCart([]);};
 return <div className="page"><header><h1>ShopSphere</h1><span>DevOps Practice E-commerce</span></header><main><section className="panel"><h2>Demo User</h2><div className="form"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Name"/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" type="password"/><button onClick={register}>{user?'Registered':'Register'}</button></div></section><section><h2>Products</h2><div className="grid">{products.map(p=><article className="card" key={p.id}><h3>{p.name}</h3><p>{p.description}</p><b>₹{Number(p.price).toFixed(2)}</b><small>{p.category} · {p.inventory} in stock</small><button onClick={()=>add(p)}>Add to cart</button></article>)}</div></section><section className="panel"><h2>Cart ({cart.reduce((s,i)=>s+i.quantity,0)})</h2>{cart.map(i=><div className="line" key={i.id}><span>{i.name} × {i.quantity}</span><span>₹{(Number(i.price)*i.quantity).toFixed(2)}</span></div>)}<button disabled={!cart.length} onClick={checkout}>Place Order</button>{message&&<p className="message">{message}</p>}</section></main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
